# Generated by Django 4.1 on 2022-09-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_cliente', models.CharField(max_length=33)),
                ('Email_cliente', models.EmailField(max_length=254, unique=True)),
                ('Dni_cliente', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_empleado', models.CharField(max_length=33)),
                ('Dni_empleado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Linea_telefonica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_celular', models.IntegerField(unique=True)),
                ('Ex_compañia', models.CharField(max_length=33)),
            ],
        ),
    ]
